name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode Service Account Key
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > service-account-key.json

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Decrypt Secrets
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="service-account-key.json"
        sops --decrypt dev_secret.enc.yaml > dev_secret.yaml

    - name: Use Decrypted Secrets
      run: |
        cat dev_secret.yaml
