name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sops
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y gnupg2 curl

        # Download and install sops
        curl -Lo /tmp/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
        sudo mv /tmp/sops /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # - name: Decrypt Secrets
    #   run: |
    #     sops --decrypt dev_secret.enc.yaml > dev_secret.yaml
    - name: Decrypt Secrets using GCP KMS
      run: |
        # Extract KMS details from secret (e.g., gcp_KMS)
        KMS_DETAILS=${{ secrets.GCP_KMS }}
        
        # Split the KMS details into individual components (keyring, key, location, project)
        KMS_KEYRING=$(echo $KMS_DETAILS | jq -r '.keyring')
        KMS_KEY=$(echo $KMS_DETAILS | jq -r '.key')
        KMS_LOCATION=$(echo $KMS_DETAILS | jq -r '.location')
        KMS_PROJECT=$(echo $KMS_DETAILS | jq -r '.project')

        # Use the extracted values to run the decryption
        gcloud kms decrypt \
          --ciphertext-file=dev_secret.enc.yaml \
          --plaintext-file=dev_secret.yaml \
          --location=$KMS_LOCATION \
          --keyring=$KMS_KEYRING \
          --key=$KMS_KEY \
          --project=$KMS_PROJECT

    - name: Use Decrypted Secrets
      run: |
        cat dev_secret.yaml
