name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

      # Install Mozilla Sops Binary
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 'v3.7.3' # default is latest stable
        id: install

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # - name: Decrypt Secrets
    #   run: |
        # sops --decrypt dev_secret.enc.yaml > dev_secret.yaml
    - name: Decrypt Secrets using GCP KMS
      run: |
        sops --decrypt --gcp-kms "${{ secrets.GCP_KMS }}" dev_secret.enc.yaml > dev_secret.yaml

    - name: Use Decrypted Secrets
      run: |
        cat dev_secret.yaml
