name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sops
      run: |
        sudo apt-get update
        sudo apt-get install -y sops

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Decrypt Secrets
      run: |
        sops --decrypt dev_secret.enc.yaml > dev_secret.yaml

    - name: Use Decrypted Secrets
      run: |
        cat dev_secret.yaml
