name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Mozilla Sops Binary
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 'v3.7.3' # Specify the version of SOPS
        id: install

      # Step 3: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 4: Decrypt Secrets using GCP KMS
      - name: Decrypt Secrets using GCP KMS
        run: |
          sops --decrypt --gcp-kms "${{ secrets.GCP_KMS }}" dev_secret.enc.yaml > dev_secret.yaml

      # Step 5: Use Decrypted Secrets
      - name: Use Decrypted Secrets
        run: |
          cat dev_secret.yaml
