name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sops
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y gnupg2 curl

        # Download and install sops
        curl -Lo /tmp/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
        sudo mv /tmp/sops /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Decrypt Secrets
      run: |
        sops --decrypt dev_secret.enc.yaml > dev_secret.yaml

    - name: Use Decrypted Secrets
      run: |
        cat dev_secret.yaml
