name: Decrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Install Dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y curl jq

    # - name: Install Google Cloud SDK
    #   run: |
    #     curl https://sdk.cloud.google.com | bash
    #     source $HOME/google-cloud-sdk/path.bash.inc
    #     gcloud components install beta

    - name: Install sops
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y gnupg2 curl

        # Download and install sops
        curl -Lo /tmp/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
        sudo mv /tmp/sops /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # - name: Decrypt Secrets
    #   run: |
    #     sops --decrypt dev_secret.enc.yaml > dev_secret.yaml
    - name: Decrypt Secrets using GCP KMS
      run: |
        # Use the full KMS key path directly from the GitHub secret
        KMS_KEY_PATH="${{ secrets.GCP_KMS }}"

        echo "KMS Key Path: $KMS_KEY_PATH"

        # Parse the KMS key path into individual components using awk
        KMS_PROJECT=$(echo $KMS_KEY_PATH | awk -F'/' '{print $2}')
        KMS_LOCATION=$(echo $KMS_KEY_PATH | awk -F'/' '{print $4}')
        KMS_KEYRING=$(echo $KMS_KEY_PATH | awk -F'/' '{print $6}')
        KMS_KEY=$(echo $KMS_KEY_PATH | awk -F'/' '{print $8}')

        echo "Project: $KMS_PROJECT"
        echo "Location: $KMS_LOCATION"
        echo "Keyring: $KMS_KEYRING"
        echo "Key: $KMS_KEY"

    - name: Use Decrypted Secrets
      run: |
        cat dev_secret.yaml
